apiVersion: v1
kind: ConfigMap
metadata:
  name: sweater-config
  namespace: sweater
data:
  POSTGRES_DB: "sweater"
  POSTGRES_USER: "postgres"
  DB_HOST: "postgres"
  DB_PORT: "5432"
  STORAGE_TYPE: "local"
  FLASK_ENV: "production"
